spring:
  application:
    name: parking-meter

  datasource:
    url: jdbc:mysql://localhost:3306/meter
    username: user
    password: secret

  exposed:
    show-sql: true
    generate-ddl: true

  data:
    redis:
      client-type: lettuce
      host: localhost
      port: 6379
      database: 0